### ISSUE TITLE
Seeking with "AES/CBC/PKCS5Padding" Cipher generates java.io.EOFException

### ISSUE THREAD

**Issue by jpfourny** [palantir/hadoop-crypto#101]
I have had no luck with seeking on encrypted file streams when using the "AES/CBC/PKCS5Padding" cipher. On the other hand, the "AES/CTR/NoPadding" cipher works 100% of the time. My case is using StandaloneEncryptedFileSystem to write a parquet file to encrypted local file system and then reading the parquet file. One of the first things done with the parquet reader is to read the footer (one of the last records). This is where it is always failing for me. Seeking to the footer is hitting a premature EOF, typically 2 bytes short. I suspect this has something to do with the padding. FYI, I am using the latest IBM JDK (not Oracle or OpenJDK) ... not that it should make any difference. Any ideas? Should I create a simplified test case for you?

**Comment by uschi2000** [comment]
Can you provide a failing test case, please?

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by ellisjoe** [comment]
As mentioned this is the result of the additional padding. The seeking spark is doing uses the FileStatus to determine where the end of the stream is and that will include the padding bytes. Is there any you can't just use CTR mode?

**Comment by ellisjoe** [comment]
Closing this since there's nothing we can do without storing the unencrypted file size somewhere. If you need the ability to seek to the end of the file you can use `AES/CTR/NoPadding` which is the recommended cipher.
