### ISSUE TITLE
AesCbcCipher and AesCtrCipher to support key sizes less than 256.

### ISSUE THREAD

**Issue by miccagiann** [palantir/hadoop-crypto#107]
Hi guys,

Are you planning on making the KEY_SIZE static field modifiable so as this library to work when running on JREs/JVMs that do not ship with the enhanced security files? If not, is it something that you feel it is worth contributing back to the project if I coded myself?

Thanks!

**Comment by schlosna** [comment]
Worth noting that Oracle Java 8u161/8u162 & 9.0.4 and corresponding OpenJDK all now enable unlimited crypto by default, see https://bugs.openjdk.java.net/browse/JDK-8170157

**Comment by uschi2000** [comment]
If I remember correctly, smaller ciphers are known to be broken, so I don't think we want to support them.

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by miccagiann** [comment]
Thanks for the reply guys!

What if someone needs to work with Java 7-8 JREs/JDKs that are not so new and cannot have access to the machines that they are installed in order to update them with unrestricted policy files? Currently, in this scenario a hard error is being thrown, while in a less aggressive scenario you could enable security using 128 as key length but throw a big fat warning to the user that he/she should consider to install the unrestricted policy files... I believe it is worth addressing this issue in terms of the aforementioned scenarios. What do you think?

**Comment by uschi2000** [comment]
We prefer failing hard and early in this case since running with 128bit keys is not acceptable, sorry.

**Comment by ellisjoe** [comment]
So went digging for reasons why we should force 256 bit keys and ended up just finding things that say 128 bit keys are fine.

Page 67 Table 4: 128, 192, 256 bit keys are all acceptable beyond 2031
https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-57p1r3.pdf

Interestingly there was an attack that affected only 256 bit keys:
https://www.schneier.com/blog/archives/2009/07/another_new_aes.html

And a more recent post recommending the same thing "And for new applications I suggest that people don't use AES-256. AES-128 provides more than enough security margin for the forseeable future. But if you're already using AES-256, there's no reason to change."
https://www.schneier.com/blog/archives/2011/08/new_attack_on_a_1.html

At this point I'm not opposed to allowing 128 bit keys, though I'd like input from some others.

**Comment by ellisjoe** [comment]
@miccagiann if you want to use 128 bit keys you can set the environment variable `OVERRIDE_KEY_SAFETY_PROTECTIONS=true` as seen here: https://github.com/palantir/hadoop-crypto/blob/develop/verify-ibmjvm.sh#L9
