### ISSUE TITLE
reading 512 bytes at a time

### ISSUE THREAD

**Issue by sjrand** [palantir/hadoop-crypto#58]
BLUF: Applications that use this library will attempt to read at most 512 bytes at a time, likely due to the behavior of `CipherInputStream`. I will stop neglecting https://github.com/palantir/hadoop-crypto/pull/35, and try to get that over the line asap.

Earlier today I was investigating the impact of setting `fs.s3a.experimental.input.fadvise` equal to `random` for a Spark application that reads Parquet files from an S3 bucket. This is one of the cooler new features in Hadoop 2.8.0, and I was hoping to observe a noticeable improvement in read performance. Disappointingly and confusingly, reads actually became much slower unless I changed the value of `fs.s3a.readahead.range` to something much larger than the default, which is 64 kb.

`DEBUG` logging for `org.apache.hadoop.s3a` on the Spark executors indicated that the `S3AInputStream` for the object being read was being closed and reopened many times. This doesn't really make sense, since the number of bytes that s3a will request in this case is the [maximum of the readahead and value and the length that the application is requesting](https://github.com/palantir/hadoop/blob/branch-2.8.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L673). No matter how ridiculously small the readahead, the stream should not be closed and reopened repeatedly unless the client is reading in small chunks.

A closer look at the `DEBUG` logging on [S3AInputStream#reopen](https://github.com/palantir/hadoop/blob/branch-2.8.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L146) indicated that the value of the `length` variable was `512` for each read. That is, the client was reading 512 bytes, closing the stream, reopening it to read another 512 bytes, and so on. (EDIT: The client was requesting 512 bytes at a time, but s3a was reading 64 kb at a time, since max(512,65536)=65536).

I haven't pulled out YourKit or the IntelliJ debugger, so can't confirm for certain, but I'm fairly certain after reading some code that this mysterious `512` number comes from the [ibuffer](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/javax/crypto/CipherInputStream.java?av=f#77) variable in `CipherInputStream`, and the way it's used in [CipherInputstream#read](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/javax/crypto/CipherInputStream.java?av=f#226). From what I can tell, that class will read 512 bytes at a time, and it's not configurable.

To confirm that *something* in this library -- likely but not certainly the use of `CipherInputStream` -- was the source of the `512` number, I wrote the same data into HDFS twice, once using an `hdfs://` url, and the second time using an `ehdfs://` url. I then added some logging to [DFSInputStream#read](https://github.com/palantir/hadoop/blob/branch-2.8.0/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSInputStream.java#L965) which prints the value of the `len` variable that it's given. For the `hdfs://` url, the value of `len` was consistently `65536` when I read the data, which is the value of `io.file.buffer.size` for the HDFS cluster in question. However, for the `ehdfs://` url, it was consistently `512`.

People using this library with s3a in Hadoop 2.7.3 and earlier are unaffected by this issue, as s3a will ignore the length given to it by the client, and always request the value of `getFileStatus().getLen()`. However, users of this library on Hadoop 2.8.0+ will be unable to take advantage of the random reads feature without specifying a non-default readahead range, a reasonable value for which is hard to compute given this issue. More importantly, anyone who attempts to use this library for data stored in HDFS is likely going to have a bad time.

Switching to openssl, as in https://github.com/palantir/hadoop-crypto/pull/35, is one solution, though there may be others as well.

cc some people: @schlosna @pwoody @robert3005 @ash211

**Comment by markelliot** [comment]
It's something specific to the HDFS mapping to the encryption, not the CipherInputStream. We use this library in another location to do reading and the streams don't close every 512 bytes.

**Comment by bavardage** [comment]
so hadoop 2.8.0 is looking at something like `InputStream#available`?

**Comment by ellisjoe** [comment]
Just to make sure I understand, the idea here is that S3A tries to support random seeks by basing request sizes on the number of bytes being requested by the client. So the issue is that the stack of calls looks something like:
```
Application
  -- read(10 MB) --> Hadoop-Crypto
    -- read(10 MB) --> CipherInputStream
      -- read(512 B) --> S3AInputStream
```
and therefore S3A always requests the default lower bound of 64kb.

**Comment by ellisjoe** [comment]
It would also be interesting to get stats on the parquet read pattern. eg: are there large forward seeks? backward seeks? how often and how large are they?

**Comment by ash211** [comment]
Parquet read pattern is roughly:

- read last ~byte out of the file (the footer length)
- seek backwards that amount and read the footer forward from there
- seek backwards to the ~start of the file and read data forward

**Comment by markelliot** [comment]
It sounds a lot like there's a bad choice in the s3a impl in 2.8.0 wrt requesting ranges as small as users ask for. My testing on our S3 client suggests you never really want to request less than some tradeoff point where it's about as fast to read the data as it is to make a new request. OTOH, it also pays to request the whole range on the off chance you need to read it...so it turns out the optimization needs to focus on just when to skip bytes or make a new request, and IMO should never request a bounded range.

**Comment by sjrand** [comment]
@ellisjoe, yep, that's correct. I hooked up IntelliJ to an executor, and a more granular version of the call stack for the HDFS case is:

- DecryptingSeekableInput#read with length=65536
   - CipherInputStream#read with length=65536
      - CipherInputStream#getMoreData
         - DefaultSeekableInputStream#read with length = 512
            - FsCipherInputStream$FsSeekableInput#read with length = 512
               - DFSInputStream#read with length = 512

For s3a it'll be the same, just with an `S3AInputStream` instead.

I'm not too worried about the s3a case -- we can specify a value of `fs.s3a.readahead.range` that's much larger than the default, so that at least that many bytes are always requested. (Trying to identify a good value for that parameter is what I was doing when I stumbled across this.)

However, I am concerned about the hdfs case. My understanding of what will happen there is that when a DataNode streams a block to a non-local client, the client will read the stream 512 bytes at a time. As far as I know, DFSClient doesn't have an equivalent of `S3AInputStream#calculateRequestLimit`.

**Comment by schlosna** [comment]
We should really do an audit comparing `org.apache.hadoop.crypto.CryptoInputStream` to `com.palantir.crypto2.hadoop.cipher.FsCipherInputStream` (and similar for output stream).

In this specific case `org.apache.hadoop.fs.CanSetReadahead` interface would seem to apply, though we should also look at all other implemented interfaces `Seekable, PositionedReadable, ByteBufferReadable, HasFileDescriptor, CanSetDropBehind, CanSetReadahead, HasEnhancedByteBufferAccess, ReadableByteChannel`

**Comment by markelliot** [comment]
As I noted above, there's _no_ reason not to always set up S3AInputStream to have a limit of as many bytes as the file contains. In the best case, if you read front-to-back, you never have to make a second request. In the worst case, you already had to pay the cost of closing the stream and opening a new one. In our performance tuning, we found that it's a false tradeoff to assume that you can read to the end of the stream to make the next request faster -- it's much more effective to actually consume the bytes for small distances and about as costly to consume bytes + make a new request for large distances. The best strategy we found was to allow 'small distances' to be relatively large (on the order of megabytes).

**Comment by ellisjoe** [comment]
@schlosna are you aware of any place those interfaces are utilized? Looks like `org.apache.hadoop.fs.crypto.CryptoFSDataInputStream` is the `FSDataInputStream` that will get returned by an `open` call which doesn't implement the same interfaces.

**Comment by sjrand** [comment]
Should theoretically have been fixed by #65. Need to confirm. Would also have been fixed in #35.

**Comment by sjrand** [comment]
Circling back many months later, we now read 8192 bytes at a time: https://github.com/apache/commons-crypto/blob/master/src/main/java/org/apache/commons/crypto/stream/CryptoInputStream.java#L99.

Unlike the 512 byte buffer from JCE, this one is configurable via `commons.crypto.stream.buffer.size`.

**Comment by ellisjoe** [comment]
Wasn't the original proposal just to bump the min request size in S3A?

**Comment by markelliot** [comment]
Copying from above:
> As I noted above, there's no reason not to always set up S3AInputStream to have a limit of as many bytes as the file contains. In the best case, if you read front-to-back, you never have to make a second request. In the worst case, you already had to pay the cost of closing the stream and opening a new one. In our performance tuning, we found that it's a false tradeoff to assume that you can read to the end of the stream to make the next request faster -- it's much more effective to actually consume the bytes for small distances and about as costly to consume bytes + make a new request for large distances. The best strategy we found was to allow 'small distances' to be relatively large (on the order of megabytes).

**Comment by sjrand** [comment]
Yeah, it's not actively hurting s3a, since the default behavior is to always request the whole object. It's unfortunate though that we can't at least test random reads in s3a. The thrice-repeated assertion that the feature is misguided may well be right -- I wouldn't know -- but it's contrary to all of the literature on the subject. Being able to test this feature isn't a huge deal though, so no need to push this further for purposes of s3a.

Closing this out since this doesn't seem to be actively hurting anything.

(Edited this down from a slightly longer comment for which there are maybe better forums.)
