### ISSUE TITLE
confirm perf improvements of reads after switch to OpenSSL

### ISSUE THREAD

**Issue by sjrand** [palantir/hadoop-crypto#68]
There should be substantive perf improvements on reads after #65. Need to make sure though through some testing. Should also make sure that perf is at least as good as it was on the branch for #35.

More generally, it would be amazing if there were a way to test the perf impact of changes to this library to catch regressions. Something that compares the perf of `hdfs` vs `ehdfs` or `s3a` vs `es3a` would be great, though I have no idea how one sets up such a thing in the absence of an actual HDFS cluster or S3 bucket (I doubt that fake ones running inside docker containers are particularly useful for testing perf).

**Comment by ellisjoe** [comment]
related PR: https://github.com/palantir/hadoop-crypto/pull/103
